[package]
name = "bls"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
lto = "fat"

[dependencies]
sha2 = "=0.10.8"
substrate-bn = { version = "=0.6.0" }
bn254 = "0.0.1"
risc0-zkvm = { version = "2.0", default-features = false, features = ["std", "unstable"] }

[patch.crates-io]
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
substrate-bn = { path = "../../../." }
