name: main

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    runs-on: [ self-hosted, prod, Linux, cpu ]
    env:
      RUST_BACKTRACE: full
      RISC0_SKIP_BUILD: 1
    steps:
      - uses: actions/checkout@v4
      - uses: risc0/risc0/.github/actions/rustup@352dea62857ba57331053cd0986a12c1a4708732
      - name: run tests
        run: cargo test --release -F risc0
